### ISSUE TITLE
Standard CVC should validate on both 3 and 4 digits

### ISSUE THREAD

**Issue by zkoch** [PolymerElements/gold-cc-cvc-input#18]
Standard CVC input should accept CVCs with length of either 3 or 4. Right now devs have to specify "amex" in the tag to allow 4 digits.

**Comment by notwaldorf** [comment]
You can do this by binding the `gold-cc-cvc-input`'s card type to the `gold-cc-input`'s card type:
```
<gold-cc-input auto-validate card-type="{{cardType}}"></gold-cc-input>
<gold-cc-cvc-input card-type="[[cardType]]"></gold-cc-cvc-input>
```
