### ISSUE TITLE
Should auto-bind to cardType on gold-cc-input

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/gold-cc-cvc-input#20]
Why do devs have to touch this at all? It's already a custom element, why not have the smarts built in?

Proposed behaviour:

1. Give it a `for` attribute, which takes a selector for a `<gold-cc-input>` element.
2. If that's not there, and if the parent `<form>`, [`<iron-form>`](https://elements.polymer-project.org/elements/iron-form), or non-`<form>` first parent also has a single `<gold-cc-input>` as a child, then bind to that
3. Otherwise devs are left with the current behaviour

It should, practically, also solve #18 (as it's very rare for a user to enter the CVC before the card number).

**Comment by notwaldorf** [comment]
I don't think tying them together needs to be that complicated. Since `cardType` is a notify property, you can just do something like:
```
<gold-cc-input auto-validate card-type="{{cardType}}"></gold-cc-input>
<gold-cc-cvc-input amex="[[_computeAmex(cardType)]]"></gold-cc-cvc-input>
```

I realize that's a bit annoying, however, so I'll change `gold cc-cvc-input` to have a `cardType` property instead of `amex`, so that you can just write:
```
<gold-cc-input auto-validate card-type="{{cardType}}"></gold-cc-input>
<gold-cc-cvc-input card-type="{{cardType}}"></gold-cc-cvc-input>
```
