### ISSUE TITLE
The demo is not visible in the elements catalog

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/gold-cc-cvc-input#33]
https://elements.polymer-project.org/elements/gold-cc-cvc-input

**Comment by notwaldorf** [comment]
Ah, good catch. Il'll take a look. Here's what the demo should point to, in the meantime: https://elements.polymer-project.org/elements/gold-cc-cvc-input?view=demo:demo/index.html&active=gold-cc-cvc-input

**Comment by notwaldorf** [comment]
Going to move this to the polymer-elements-catalog, since this element seems to be doing everything fine (it has an annotation, the `bower.json` looks right)

**Comment by notwaldorf** [comment]
This issue was moved to Polymer/polymer-element-catalog#243
