### ISSUE TITLE
Validation state of this and other gold-* inputs cannot be reset

### ISSUE THREAD

**Issue by ellenaua** [PolymerElements/gold-cc-cvc-input#44]
### Description

I have multiple inputs in a form, paper-* and gold-*. All of them have "auto-validate" and "required".
```
<paper-input id="name" auto-validate required></paper-input>
<gold-phone-input id="cc" auto-validate required></gold-phone-input>
<gold-cc-cvc-input id="cvc"  auto-validate required></gold-cc-cvc-input>
```
Field becomes "invalid" and highlighted with red when:
a) user clicks some input and then clicks another ("blur" happens) without typing any value
b) user enters some value which is invalid (phone, cvc)

If user just clicked and entered nothing - I want to reset this form later - to set "invalid" to false for all empty inputs. But for paper-inputs it works, for gold-inputs - does not. When I do this:
```
   this.$.name.invalid = false;
   this.$.phone.invalid = false;
   this.$.cvc.invalid = false;
```
paper input validation is reset, but gold-* inputs are still highlighted with red (they're empty). 

This inconsistency makes our interface look weird.  Especially in address forms, where some inputs are paper-* (name, address, ..) and some are gold-* (phone, cc, cvc, zip). I cannot reset form back to initial non-validated status.

### Expectations

I'd expect this logic: if gold-* input value is empty, and developer sets "invalid" to "false" - set paper-input-container.invalid to false so that validation is reset.

Here's jsbin
https://jsbin.com/zazuyi/edit?html,output

**Comment by notwaldorf** [comment]
First, if you use an `iron-form`, you can just use the form's `reset` method to do all this automatically: https://jsbin.com/loyoye/edit?html,output

Secondly, from the [docs](https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L78), if you use `auto-validate`, this will manage the `invalid` state for you, so you can't just set `invalid` and expect it to work automatically.

In the demo I sent, the `gold-phone-input` seems to reset correctly, but `gold-cc-cvc-input` does not. I'll take a look
