### ISSUE TITLE
Invalid property is only true when user has introduced and deleted input

### ISSUE THREAD

**Issue by lluissuros** [PolymerElements/gold-cc-cvc-input#52]
### Description
Invalid property is only true when user has introduced and deleted input

### Expected outcome

I would expect that invalid property is always `true` unless the user introduces a complete cvc number

### Actual outcome

Invalid is only true when cvc value is empty, but false otherwise

### Live Demo
https://jsbin.com/goxarew/edit?html,output

### Steps to reproduce

1. Put a `gold-cc-cvc-input` element in the page.
2. Introduce value `7`
3. `invalid` is false. (IMO it should be true!)
4. Delete input
5. `invalid` is true

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by lluissuros** [comment]
I submitted a PR that solves the issue:
https://github.com/PolymerElements/gold-cc-cvc-input/pull/53

Let me know what you think :)

**Comment by mcrowder65** [comment]
Thanks for fixing this with a PR, just discovered this bug a few minutes ago.

**Comment by lluissuros** [comment]
PR is merged so we can consider this closed :)
